ALTER TABLE settlements
ADD COLUMN IF NOT EXISTS actual_prod_rev_own DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_prod_rev_ext DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_svc_rev_own DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_svc_rev_ext DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_prod_cost_own DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_prod_cost_ext DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_svc_cost_own DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_svc_cost_ext DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_svc_mm_own DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_svc_mm_ext DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_expense_general DECIMAL(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_expense_special DECIMAL(15,2) DEFAULT 0;
